from .AreaBoss import DetectAreaBoss
from .Bonus import DetectBonus
from .Chapter import DetectChapter
from .Delegate import DetectDelegate
from .EvoMaterials import DetectEvoMaterials
from .Explore import DetectExplore
from .HeianStories import DetectHeianStories
from .HeianTales import DetectHeianTales
from .RealmRaid import DetectRealmRaid
from .SecretZone import DetectSecretZone
from .Souls import DetectSouls
from .Totem import DetectTotem
