from .Collection import DetectCollection
from .Earthly import DetectEarthly
from .Friend import DetectFriend
from .Guild import DetectGuild
from .Mall import DetectMall
from .Onmyoji import DetectOnmyoji
from .Pet import DetectPet
from .Shikigami import DetectShikigami
from .Summon import DetectSummon
from .FlowerFight import DetectFlowerFight
from .Team import DetectTeam
from .Yard import DetectYard
from .Invite import DetectInvite
from .BountySeals import DetectBountySeals
from .IllustratedHandbook import DetectIllustratedHandbook
from .Battle import DetectBattle
