# -*- coding: utf-8 -*-

# Form implementation generated from reading view file 'capture_tool.view'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# image_coordinate again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_CaptureTool(object):
    def setupUi(self, MainWindow_CaptureTool):
        MainWindow_CaptureTool.setObjectName("MainWindow_CaptureTool")
        MainWindow_CaptureTool.resize(311, 361)
        MainWindow_CaptureTool.setMinimumSize(QtCore.QSize(311, 361))
        MainWindow_CaptureTool.setMaximumSize(QtCore.QSize(311, 361))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        MainWindow_CaptureTool.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow_CaptureTool)
        self.centralwidget.setObjectName("centralwidget")
        self.label_window_list = QtWidgets.QLabel(self.centralwidget)
        self.label_window_list.setGeometry(QtCore.QRect(20, 80, 161, 21))
        self.label_window_list.setObjectName("label_window_list")
        self.comboBox_window_list = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_window_list.setGeometry(QtCore.QRect(20, 110, 271, 24))
        self.comboBox_window_list.setObjectName("comboBox_window_list")
        self.comboBox_json_list = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_json_list.setGeometry(QtCore.QRect(20, 180, 271, 24))
        self.comboBox_json_list.setObjectName("comboBox_json_list")
        self.label_json_list = QtWidgets.QLabel(self.centralwidget)
        self.label_json_list.setGeometry(QtCore.QRect(20, 150, 191, 21))
        self.label_json_list.setObjectName("label_json_list")
        self.pushButton_capture = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_capture.setGeometry(QtCore.QRect(20, 300, 91, 24))
        self.pushButton_capture.setObjectName("pushButton_capture")
        self.pushButton_set_coordinate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_set_coordinate.setGeometry(QtCore.QRect(200, 300, 91, 24))
        self.pushButton_set_coordinate.setObjectName("pushButton_set_coordinate")
        self.lineEdit_template_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_template_name.setGeometry(QtCore.QRect(20, 250, 271, 24))
        self.lineEdit_template_name.setObjectName("lineEdit_template_name")
        self.label_json_list_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_json_list_2.setGeometry(QtCore.QRect(20, 220, 171, 21))
        self.label_json_list_2.setObjectName("label_json_list_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 271, 61))
        self.groupBox.setObjectName("groupBox")
        self.radioButton_emulator = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_emulator.setGeometry(QtCore.QRect(190, 30, 89, 16))
        self.radioButton_emulator.setObjectName("radioButton_emulator")
        self.radioButton_sandbox_login = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_sandbox_login.setGeometry(QtCore.QRect(80, 30, 101, 16))
        self.radioButton_sandbox_login.setObjectName("radioButton_sandbox_login")
        self.radioButton_sandbox = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_sandbox.setGeometry(QtCore.QRect(0, 30, 71, 16))
        self.radioButton_sandbox.setChecked(True)
        self.radioButton_sandbox.setObjectName("radioButton_sandbox")
        MainWindow_CaptureTool.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_CaptureTool)
        self.statusbar.setObjectName("statusbar")
        MainWindow_CaptureTool.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_CaptureTool)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_CaptureTool)

    def retranslateUi(self, MainWindow_CaptureTool):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_CaptureTool.setWindowTitle(_translate("MainWindow_CaptureTool", "截图工具"))
        self.label_window_list.setText(_translate("MainWindow_CaptureTool", "请选择需要截图的程序窗口"))
        self.label_json_list.setText(_translate("MainWindow_CaptureTool", "请选择用于保存坐标的JSON文件"))
        self.pushButton_capture.setText(_translate("MainWindow_CaptureTool", "截图"))
        self.pushButton_set_coordinate.setText(_translate("MainWindow_CaptureTool", "设置区域"))
        self.label_json_list_2.setText(_translate("MainWindow_CaptureTool", "请输入截图名称(不包含后缀名)"))
        self.groupBox.setTitle(_translate("MainWindow_CaptureTool", "截图类型"))
        self.radioButton_emulator.setText(_translate("MainWindow_CaptureTool", "截图模拟器"))
        self.radioButton_sandbox_login.setText(_translate("MainWindow_CaptureTool", "截图沙箱登录"))
        self.radioButton_sandbox.setText(_translate("MainWindow_CaptureTool", "截图沙箱"))
