# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_run_env.ui'
##
## Created by: Qt User Interface Compiler version 6.4.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QGroupBox, QHeaderView,
    QLabel, QLineEdit, QMainWindow, QPushButton,
    QSizePolicy, QSpinBox, QStatusBar, QTableWidget,
    QTableWidgetItem, QWidget)

class Ui_MainWindowRunEnv(object):
    def setupUi(self, MainWindowRunEnv):
        if not MainWindowRunEnv.objectName():
            MainWindowRunEnv.setObjectName(u"MainWindowRunEnv")
        MainWindowRunEnv.resize(880, 436)
        MainWindowRunEnv.setMinimumSize(QSize(880, 436))
        MainWindowRunEnv.setMaximumSize(QSize(880, 436))
        self.centralwidget = QWidget(MainWindowRunEnv)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBox_dnplayer_path_2 = QGroupBox(self.centralwidget)
        self.groupBox_dnplayer_path_2.setObjectName(u"groupBox_dnplayer_path_2")
        self.groupBox_dnplayer_path_2.setGeometry(QRect(550, 250, 301, 51))
        font = QFont()
        font.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font.setPointSize(9)
        self.groupBox_dnplayer_path_2.setFont(font)
        self.groupBox__run_count_3 = QGroupBox(self.groupBox_dnplayer_path_2)
        self.groupBox__run_count_3.setObjectName(u"groupBox__run_count_3")
        self.groupBox__run_count_3.setEnabled(True)
        self.groupBox__run_count_3.setGeometry(QRect(10, 20, 281, 23))
        font1 = QFont()
        font1.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font1.setPointSize(8)
        self.groupBox__run_count_3.setFont(font1)
        self.spinBox_cpu_sleep_time = QSpinBox(self.groupBox__run_count_3)
        self.spinBox_cpu_sleep_time.setObjectName(u"spinBox_cpu_sleep_time")
        self.spinBox_cpu_sleep_time.setGeometry(QRect(190, 1, 51, 20))
        self.spinBox_cpu_sleep_time.setFont(font)
        self.spinBox_cpu_sleep_time.setMaximum(24)
        self.spinBox_cpu_sleep_time.setValue(7)
        self.label_scroll_count_2 = QLabel(self.groupBox__run_count_3)
        self.label_scroll_count_2.setObjectName(u"label_scroll_count_2")
        self.label_scroll_count_2.setGeometry(QRect(10, 0, 161, 21))
        self.label_scroll_count_2.setFont(font)
        self.groupBox_dnplayer_path = QGroupBox(self.centralwidget)
        self.groupBox_dnplayer_path.setObjectName(u"groupBox_dnplayer_path")
        self.groupBox_dnplayer_path.setGeometry(QRect(550, 130, 301, 51))
        self.groupBox_dnplayer_path.setFont(font)
        self.pushButton_browse_dnplayer_path = QPushButton(self.groupBox_dnplayer_path)
        self.pushButton_browse_dnplayer_path.setObjectName(u"pushButton_browse_dnplayer_path")
        self.pushButton_browse_dnplayer_path.setGeometry(QRect(240, 19, 51, 23))
        self.pushButton_browse_dnplayer_path.setFont(font)
        self.lineEdit_dnplayer_path = QLineEdit(self.groupBox_dnplayer_path)
        self.lineEdit_dnplayer_path.setObjectName(u"lineEdit_dnplayer_path")
        self.lineEdit_dnplayer_path.setGeometry(QRect(10, 20, 231, 21))
        font2 = QFont()
        font2.setFamilies([u"\u5b8b\u4f53"])
        font2.setPointSize(9)
        self.lineEdit_dnplayer_path.setFont(font2)
        self.lineEdit_dnplayer_path.setReadOnly(True)
        self.groupBox_play_list_11 = QGroupBox(self.centralwidget)
        self.groupBox_play_list_11.setObjectName(u"groupBox_play_list_11")
        self.groupBox_play_list_11.setGeometry(QRect(280, 10, 251, 381))
        self.groupBox_play_list_11.setFont(font)
        self.tableWidget_sandbox = QTableWidget(self.groupBox_play_list_11)
        self.tableWidget_sandbox.setObjectName(u"tableWidget_sandbox")
        self.tableWidget_sandbox.setGeometry(QRect(0, 20, 251, 361))
        self.tableWidget_sandbox.setFont(font)
        self.tableWidget_sandbox.setContextMenuPolicy(Qt.CustomContextMenu)
        self.tableWidget_sandbox.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget_sandbox.setSelectionMode(QAbstractItemView.ExtendedSelection)
        self.tableWidget_sandbox.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableWidget_sandbox.setVerticalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_sandbox.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_sandbox.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_sandbox.horizontalHeader().setDefaultSectionSize(70)
        self.tableWidget_sandbox.horizontalHeader().setHighlightSections(False)
        self.tableWidget_sandbox.verticalHeader().setVisible(False)
        self.tableWidget_sandbox.verticalHeader().setMinimumSectionSize(18)
        self.tableWidget_sandbox.verticalHeader().setDefaultSectionSize(18)
        self.groupBox_dnplayer_path_3 = QGroupBox(self.centralwidget)
        self.groupBox_dnplayer_path_3.setObjectName(u"groupBox_dnplayer_path_3")
        self.groupBox_dnplayer_path_3.setGeometry(QRect(550, 70, 301, 51))
        self.groupBox_dnplayer_path_3.setFont(font)
        self.pushButton_browse_sandbox_path = QPushButton(self.groupBox_dnplayer_path_3)
        self.pushButton_browse_sandbox_path.setObjectName(u"pushButton_browse_sandbox_path")
        self.pushButton_browse_sandbox_path.setGeometry(QRect(240, 19, 51, 23))
        self.pushButton_browse_sandbox_path.setFont(font)
        self.lineEdit_sandbox_path = QLineEdit(self.groupBox_dnplayer_path_3)
        self.lineEdit_sandbox_path.setObjectName(u"lineEdit_sandbox_path")
        self.lineEdit_sandbox_path.setGeometry(QRect(10, 20, 231, 21))
        self.lineEdit_sandbox_path.setFont(font2)
        self.lineEdit_sandbox_path.setReadOnly(True)
        self.groupBox_play_list_9 = QGroupBox(self.centralwidget)
        self.groupBox_play_list_9.setObjectName(u"groupBox_play_list_9")
        self.groupBox_play_list_9.setGeometry(QRect(10, 10, 251, 381))
        self.groupBox_play_list_9.setFont(font)
        self.tableWidget_emulator = QTableWidget(self.groupBox_play_list_9)
        self.tableWidget_emulator.setObjectName(u"tableWidget_emulator")
        self.tableWidget_emulator.setGeometry(QRect(0, 20, 251, 361))
        self.tableWidget_emulator.setFont(font)
        self.tableWidget_emulator.setContextMenuPolicy(Qt.CustomContextMenu)
        self.tableWidget_emulator.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget_emulator.setSelectionMode(QAbstractItemView.ExtendedSelection)
        self.tableWidget_emulator.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableWidget_emulator.setVerticalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_emulator.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_emulator.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_emulator.horizontalHeader().setDefaultSectionSize(70)
        self.tableWidget_emulator.horizontalHeader().setHighlightSections(False)
        self.tableWidget_emulator.verticalHeader().setVisible(False)
        self.tableWidget_emulator.verticalHeader().setMinimumSectionSize(18)
        self.tableWidget_emulator.verticalHeader().setDefaultSectionSize(18)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(550, 320, 301, 61))
        self.spinBox_offset_x = QSpinBox(self.groupBox)
        self.spinBox_offset_x.setObjectName(u"spinBox_offset_x")
        self.spinBox_offset_x.setGeometry(QRect(40, 30, 71, 20))
        self.spinBox_offset_x.setFont(font)
        self.spinBox_offset_x.setMinimum(-8192)
        self.spinBox_offset_x.setMaximum(8192)
        self.spinBox_offset_x.setValue(0)
        self.spinBox_offset_y = QSpinBox(self.groupBox)
        self.spinBox_offset_y.setObjectName(u"spinBox_offset_y")
        self.spinBox_offset_y.setGeometry(QRect(180, 30, 71, 20))
        self.spinBox_offset_y.setFont(font)
        self.spinBox_offset_y.setMinimum(-8192)
        self.spinBox_offset_y.setMaximum(8192)
        self.spinBox_offset_y.setValue(0)
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 30, 21, 21))
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(160, 30, 21, 21))
        self.groupBox_31 = QGroupBox(self.centralwidget)
        self.groupBox_31.setObjectName(u"groupBox_31")
        self.groupBox_31.setGeometry(QRect(550, 190, 301, 51))
        self.groupBox_31.setFont(font)
        self.groupBox__run_count_2 = QGroupBox(self.groupBox_31)
        self.groupBox__run_count_2.setObjectName(u"groupBox__run_count_2")
        self.groupBox__run_count_2.setEnabled(True)
        self.groupBox__run_count_2.setGeometry(QRect(140, 20, 151, 23))
        self.groupBox__run_count_2.setFont(font1)
        self.spinBox_scroll_time = QSpinBox(self.groupBox__run_count_2)
        self.spinBox_scroll_time.setObjectName(u"spinBox_scroll_time")
        self.spinBox_scroll_time.setGeometry(QRect(60, 1, 51, 20))
        self.spinBox_scroll_time.setFont(font)
        self.spinBox_scroll_time.setMinimum(1)
        self.spinBox_scroll_time.setMaximum(1440)
        self.spinBox_scroll_time.setValue(60)
        self.label_scroll_time = QLabel(self.groupBox__run_count_2)
        self.label_scroll_time.setObjectName(u"label_scroll_time")
        self.label_scroll_time.setGeometry(QRect(10, 0, 61, 21))
        self.label_scroll_time.setFont(font)
        self.label_run_count_3 = QLabel(self.groupBox__run_count_2)
        self.label_run_count_3.setObjectName(u"label_run_count_3")
        self.label_run_count_3.setGeometry(QRect(120, 0, 31, 21))
        self.label_run_count_3.setFont(font)
        self.groupBox__run_count = QGroupBox(self.groupBox_31)
        self.groupBox__run_count.setObjectName(u"groupBox__run_count")
        self.groupBox__run_count.setEnabled(True)
        self.groupBox__run_count.setGeometry(QRect(10, 20, 121, 23))
        self.groupBox__run_count.setFont(font1)
        self.spinBox_scroll_count = QSpinBox(self.groupBox__run_count)
        self.spinBox_scroll_count.setObjectName(u"spinBox_scroll_count")
        self.spinBox_scroll_count.setGeometry(QRect(80, 1, 41, 20))
        self.spinBox_scroll_count.setFont(font)
        self.spinBox_scroll_count.setMaximum(99)
        self.spinBox_scroll_count.setValue(10)
        self.label_scroll_count = QLabel(self.groupBox__run_count)
        self.label_scroll_count.setObjectName(u"label_scroll_count")
        self.label_scroll_count.setGeometry(QRect(10, 0, 61, 21))
        self.label_scroll_count.setFont(font)
        self.groupBox_dnplayer_path_4 = QGroupBox(self.centralwidget)
        self.groupBox_dnplayer_path_4.setObjectName(u"groupBox_dnplayer_path_4")
        self.groupBox_dnplayer_path_4.setGeometry(QRect(550, 10, 301, 51))
        self.groupBox_dnplayer_path_4.setFont(font)
        self.pushButton_browse_onmyoji_pc_path = QPushButton(self.groupBox_dnplayer_path_4)
        self.pushButton_browse_onmyoji_pc_path.setObjectName(u"pushButton_browse_onmyoji_pc_path")
        self.pushButton_browse_onmyoji_pc_path.setGeometry(QRect(240, 19, 51, 23))
        self.pushButton_browse_onmyoji_pc_path.setFont(font)
        self.lineEdit_onmyoji_pc_path = QLineEdit(self.groupBox_dnplayer_path_4)
        self.lineEdit_onmyoji_pc_path.setObjectName(u"lineEdit_onmyoji_pc_path")
        self.lineEdit_onmyoji_pc_path.setGeometry(QRect(10, 20, 231, 21))
        self.lineEdit_onmyoji_pc_path.setFont(font2)
        self.lineEdit_onmyoji_pc_path.setReadOnly(True)
        MainWindowRunEnv.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindowRunEnv)
        self.statusbar.setObjectName(u"statusbar")
        MainWindowRunEnv.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowRunEnv)

        QMetaObject.connectSlotsByName(MainWindowRunEnv)
    # setupUi

    def retranslateUi(self, MainWindowRunEnv):
        MainWindowRunEnv.setWindowTitle(QCoreApplication.translate("MainWindowRunEnv", u"\u8fd0\u884c\u73af\u5883", None))
        self.groupBox_dnplayer_path_2.setTitle(QCoreApplication.translate("MainWindowRunEnv", u"CPU\u8c03\u8282", None))
        self.groupBox__run_count_3.setTitle("")
        self.label_scroll_count_2.setText(QCoreApplication.translate("MainWindowRunEnv", u"\u6570\u503c\u8d8a\u5927\u5360\u7528\u8d8a\u5c0f\uff0c\u6267\u884c\u8d8a\u6162", None))
        self.groupBox_dnplayer_path.setTitle(QCoreApplication.translate("MainWindowRunEnv", u"\u96f7\u7535\u6a21\u62df\u5668\u8def\u5f84", None))
        self.pushButton_browse_dnplayer_path.setText(QCoreApplication.translate("MainWindowRunEnv", u"\u6d4f\u89c8", None))
        self.lineEdit_dnplayer_path.setText("")
        self.groupBox_play_list_11.setTitle(QCoreApplication.translate("MainWindowRunEnv", u"sandbox\u5217\u8868", None))
        self.groupBox_dnplayer_path_3.setTitle(QCoreApplication.translate("MainWindowRunEnv", u"sandbox\u8def\u5f84", None))
        self.pushButton_browse_sandbox_path.setText(QCoreApplication.translate("MainWindowRunEnv", u"\u6d4f\u89c8", None))
        self.lineEdit_sandbox_path.setText("")
        self.groupBox_play_list_9.setTitle(QCoreApplication.translate("MainWindowRunEnv", u"\u6a21\u62df\u5668\u5217\u8868", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindowRunEnv", u"\u6392\u5e8f\u504f\u79fb", None))
        self.label.setText(QCoreApplication.translate("MainWindowRunEnv", u"X:", None))
        self.label_2.setText(QCoreApplication.translate("MainWindowRunEnv", u"Y:", None))
        self.groupBox_31.setTitle(QCoreApplication.translate("MainWindowRunEnv", u"\u8f6e\u6362\u8bbe\u7f6e", None))
        self.groupBox__run_count_2.setTitle("")
        self.label_scroll_time.setText(QCoreApplication.translate("MainWindowRunEnv", u"\u6267\u884c\u65f6\u957f", None))
        self.label_run_count_3.setText(QCoreApplication.translate("MainWindowRunEnv", u"\u5206\u949f", None))
        self.groupBox__run_count.setTitle("")
        self.label_scroll_count.setText(QCoreApplication.translate("MainWindowRunEnv", u"\u540c\u65f6\u6267\u884c\u6570", None))
        self.groupBox_dnplayer_path_4.setTitle(QCoreApplication.translate("MainWindowRunEnv", u"\u6e38\u620fPC\u7aef\u8def\u5f84", None))
        self.pushButton_browse_onmyoji_pc_path.setText(QCoreApplication.translate("MainWindowRunEnv", u"\u6d4f\u89c8", None))
        self.lineEdit_onmyoji_pc_path.setText("")
    # retranslateUi

