# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.3.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QCheckBox, QComboBox,
    QGroupBox, QHeaderView, QLabel, QLineEdit,
    QMainWindow, QPushButton, QRadioButton, QSizePolicy,
    QSpinBox, QStatusBar, QTabWidget, QTableWidget,
    QTableWidgetItem, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(880, 460)
        MainWindow.setMinimumSize(QSize(880, 460))
        MainWindow.setMaximumSize(QSize(880, 460))
        font = QFont()
        font.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font.setPointSize(8)
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QRect(10, 10, 871, 421))
        self.tabWidget.setMinimumSize(QSize(0, 390))
        self.tabWidget.setMaximumSize(QSize(16777215, 16777215))
        font1 = QFont()
        font1.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font1.setPointSize(9)
        self.tabWidget.setFont(font1)
        self.tab_run_list = QWidget()
        self.tab_run_list.setObjectName(u"tab_run_list")
        self.tableWidget_run_list = QTableWidget(self.tab_run_list)
        self.tableWidget_run_list.setObjectName(u"tableWidget_run_list")
        self.tableWidget_run_list.setGeometry(QRect(0, 10, 781, 381))
        self.tableWidget_run_list.setMinimumSize(QSize(0, 0))
        self.tableWidget_run_list.setSizeIncrement(QSize(0, 0))
        font2 = QFont()
        font2.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font2.setPointSize(9)
        font2.setBold(False)
        self.tableWidget_run_list.setFont(font2)
        self.tableWidget_run_list.setTabletTracking(False)
        self.tableWidget_run_list.setContextMenuPolicy(Qt.CustomContextMenu)
        self.tableWidget_run_list.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.tableWidget_run_list.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget_run_list.setSelectionMode(QAbstractItemView.ExtendedSelection)
        self.tableWidget_run_list.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableWidget_run_list.setVerticalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_run_list.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_run_list.setGridStyle(Qt.SolidLine)
        self.tableWidget_run_list.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_run_list.horizontalHeader().setDefaultSectionSize(45)
        self.tableWidget_run_list.horizontalHeader().setHighlightSections(False)
        self.tableWidget_run_list.verticalHeader().setVisible(False)
        self.tableWidget_run_list.verticalHeader().setMinimumSectionSize(18)
        self.tableWidget_run_list.verticalHeader().setDefaultSectionSize(18)
        self.tableWidget_run_list.verticalHeader().setHighlightSections(True)
        self.tableWidget_run_count = QTableWidget(self.tab_run_list)
        self.tableWidget_run_count.setObjectName(u"tableWidget_run_count")
        self.tableWidget_run_count.setGeometry(QRect(780, 10, 82, 381))
        self.tableWidget_run_count.setFont(font)
        self.tableWidget_run_count.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableWidget_run_count.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget_run_count.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableWidget_run_count.horizontalHeader().setVisible(True)
        self.tableWidget_run_count.horizontalHeader().setMinimumSectionSize(40)
        self.tableWidget_run_count.horizontalHeader().setDefaultSectionSize(40)
        self.tableWidget_run_count.horizontalHeader().setHighlightSections(False)
        self.tableWidget_run_count.verticalHeader().setVisible(False)
        self.tableWidget_run_count.verticalHeader().setMinimumSectionSize(16)
        self.tableWidget_run_count.verticalHeader().setDefaultSectionSize(16)
        self.tabWidget.addTab(self.tab_run_list, "")
        self.tab_products = QWidget()
        self.tab_products.setObjectName(u"tab_products")
        self.groupBox_play_list = QGroupBox(self.tab_products)
        self.groupBox_play_list.setObjectName(u"groupBox_play_list")
        self.groupBox_play_list.setGeometry(QRect(10, 10, 851, 191))
        self.groupBox_play_list.setFont(font1)
        self.tableWidget_products = QTableWidget(self.groupBox_play_list)
        self.tableWidget_products.setObjectName(u"tableWidget_products")
        self.tableWidget_products.setGeometry(QRect(0, 20, 851, 171))
        self.tableWidget_products.setFont(font1)
        self.tableWidget_products.setContextMenuPolicy(Qt.CustomContextMenu)
        self.tableWidget_products.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget_products.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableWidget_products.setVerticalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_products.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_products.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_products.horizontalHeader().setDefaultSectionSize(50)
        self.tableWidget_products.horizontalHeader().setHighlightSections(False)
        self.tableWidget_products.verticalHeader().setVisible(False)
        self.tableWidget_products.verticalHeader().setMinimumSectionSize(18)
        self.tableWidget_products.verticalHeader().setDefaultSectionSize(18)
        self.groupBox_3 = QGroupBox(self.tab_products)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 200, 161, 191))
        self.groupBox_3.setFont(font1)
        self.label = QLabel(self.groupBox_3)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 20, 31, 21))
        self.label.setFont(font1)
        self.comboBox_job_option_play = QComboBox(self.groupBox_3)
        self.comboBox_job_option_play.setObjectName(u"comboBox_job_option_play")
        self.comboBox_job_option_play.setGeometry(QRect(40, 20, 111, 20))
        self.comboBox_job_option_play.setFont(font1)
        self.label_2 = QLabel(self.groupBox_3)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 110, 31, 21))
        self.label_2.setFont(font1)
        self.lineEdit_count = QLineEdit(self.groupBox_3)
        self.lineEdit_count.setObjectName(u"lineEdit_count")
        self.lineEdit_count.setGeometry(QRect(40, 110, 111, 20))
        self.lineEdit_count.setFont(font1)
        self.lineEdit_count.setAlignment(Qt.AlignCenter)
        self.label_3 = QLabel(self.groupBox_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 80, 31, 21))
        self.label_3.setFont(font1)
        self.comboBox_job_option_stage = QComboBox(self.groupBox_3)
        self.comboBox_job_option_stage.setObjectName(u"comboBox_job_option_stage")
        self.comboBox_job_option_stage.setGeometry(QRect(40, 80, 111, 20))
        self.comboBox_job_option_stage.setFont(font1)
        self.pushButton_save_job = QPushButton(self.groupBox_3)
        self.pushButton_save_job.setObjectName(u"pushButton_save_job")
        self.pushButton_save_job.setGeometry(QRect(100, 160, 51, 23))
        self.pushButton_save_job.setFont(font1)
        self.pushButton_reset_job_option = QPushButton(self.groupBox_3)
        self.pushButton_reset_job_option.setObjectName(u"pushButton_reset_job_option")
        self.pushButton_reset_job_option.setGeometry(QRect(40, 160, 51, 23))
        self.pushButton_reset_job_option.setFont(font1)
        self.label_4 = QLabel(self.groupBox_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 50, 31, 21))
        self.label_4.setFont(font1)
        self.comboBox_job_option_play_sub = QComboBox(self.groupBox_3)
        self.comboBox_job_option_play_sub.setObjectName(u"comboBox_job_option_play_sub")
        self.comboBox_job_option_play_sub.setGeometry(QRect(40, 50, 111, 20))
        self.comboBox_job_option_play_sub.setFont(font1)
        self.checkBox_job_option_approximate_count = QCheckBox(self.groupBox_3)
        self.checkBox_job_option_approximate_count.setObjectName(u"checkBox_job_option_approximate_count")
        self.checkBox_job_option_approximate_count.setEnabled(True)
        self.checkBox_job_option_approximate_count.setGeometry(QRect(40, 130, 111, 21))
        self.checkBox_job_option_approximate_count.setFont(font2)
        self.groupBox_play_list_setting = QGroupBox(self.tab_products)
        self.groupBox_play_list_setting.setObjectName(u"groupBox_play_list_setting")
        self.groupBox_play_list_setting.setGeometry(QRect(170, 200, 611, 201))
        self.groupBox_play_list_setting.setFont(font2)
        self.groupBox_play_list_setting.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.checkBox_job_option_bonus_exp_100 = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_bonus_exp_100.setObjectName(u"checkBox_job_option_bonus_exp_100")
        self.checkBox_job_option_bonus_exp_100.setEnabled(True)
        self.checkBox_job_option_bonus_exp_100.setGeometry(QRect(10, 170, 71, 21))
        self.checkBox_job_option_bonus_exp_100.setFont(font2)
        self.checkBox_job_option_bonus_exp_50 = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_bonus_exp_50.setObjectName(u"checkBox_job_option_bonus_exp_50")
        self.checkBox_job_option_bonus_exp_50.setEnabled(True)
        self.checkBox_job_option_bonus_exp_50.setGeometry(QRect(10, 140, 71, 21))
        self.checkBox_job_option_bonus_exp_50.setFont(font2)
        self.checkBox_job_option_bonus_coin_100 = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_bonus_coin_100.setObjectName(u"checkBox_job_option_bonus_coin_100")
        self.checkBox_job_option_bonus_coin_100.setEnabled(True)
        self.checkBox_job_option_bonus_coin_100.setGeometry(QRect(10, 110, 71, 21))
        self.checkBox_job_option_bonus_coin_100.setFont(font2)
        self.checkBox_job_option_bonus_evolution = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_bonus_evolution.setObjectName(u"checkBox_job_option_bonus_evolution")
        self.checkBox_job_option_bonus_evolution.setEnabled(True)
        self.checkBox_job_option_bonus_evolution.setGeometry(QRect(10, 50, 71, 21))
        self.checkBox_job_option_bonus_evolution.setFont(font2)
        self.checkBox_job_option_bonus_coin_50 = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_bonus_coin_50.setObjectName(u"checkBox_job_option_bonus_coin_50")
        self.checkBox_job_option_bonus_coin_50.setEnabled(True)
        self.checkBox_job_option_bonus_coin_50.setGeometry(QRect(10, 80, 71, 21))
        self.checkBox_job_option_bonus_coin_50.setFont(font2)
        self.checkBox_job_option_bonus_soul = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_bonus_soul.setObjectName(u"checkBox_job_option_bonus_soul")
        self.checkBox_job_option_bonus_soul.setEnabled(True)
        self.checkBox_job_option_bonus_soul.setGeometry(QRect(10, 20, 71, 21))
        self.checkBox_job_option_bonus_soul.setFont(font2)
        self.checkBox_job_option_chapter_gift_spirit = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_chapter_gift_spirit.setObjectName(u"checkBox_job_option_chapter_gift_spirit")
        self.checkBox_job_option_chapter_gift_spirit.setGeometry(QRect(90, 110, 61, 21))
        self.checkBox_job_option_chapter_gift_spirit.setFont(font2)
        self.checkBox_job_option_chapter_gift_spirit.setChecked(False)
        self.checkBox_job_option_chapter_exp_spirit = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_chapter_exp_spirit.setObjectName(u"checkBox_job_option_chapter_exp_spirit")
        self.checkBox_job_option_chapter_exp_spirit.setGeometry(QRect(90, 50, 61, 21))
        self.checkBox_job_option_chapter_exp_spirit.setFont(font2)
        self.checkBox_job_option_chapter_exp_spirit.setChecked(False)
        self.checkBox_job_option_chapter_all_spirit = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_chapter_all_spirit.setObjectName(u"checkBox_job_option_chapter_all_spirit")
        self.checkBox_job_option_chapter_all_spirit.setGeometry(QRect(90, 20, 61, 21))
        self.checkBox_job_option_chapter_all_spirit.setFont(font2)
        self.checkBox_job_option_chapter_all_spirit.setChecked(False)
        self.checkBox_job_option_chapter_coin_spirit = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_chapter_coin_spirit.setObjectName(u"checkBox_job_option_chapter_coin_spirit")
        self.checkBox_job_option_chapter_coin_spirit.setGeometry(QRect(90, 80, 61, 21))
        self.checkBox_job_option_chapter_coin_spirit.setFont(font2)
        self.checkBox_job_option_chapter_coin_spirit.setChecked(False)
        self.checkBox_job_option_chapter_map_gift = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_chapter_map_gift.setObjectName(u"checkBox_job_option_chapter_map_gift")
        self.checkBox_job_option_chapter_map_gift.setGeometry(QRect(90, 140, 61, 21))
        self.checkBox_job_option_chapter_map_gift.setFont(font2)
        self.checkBox_job_option_chapter_map_seal = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_chapter_map_seal.setObjectName(u"checkBox_job_option_chapter_map_seal")
        self.checkBox_job_option_chapter_map_seal.setGeometry(QRect(90, 170, 61, 21))
        self.checkBox_job_option_chapter_map_seal.setFont(font2)
        self.groupBox_play_list_chapter = QGroupBox(self.groupBox_play_list_setting)
        self.groupBox_play_list_chapter.setObjectName(u"groupBox_play_list_chapter")
        self.groupBox_play_list_chapter.setGeometry(QRect(230, 20, 75, 51))
        self.radioButton_job_option_dog_food_m = QRadioButton(self.groupBox_play_list_chapter)
        self.radioButton_job_option_dog_food_m.setObjectName(u"radioButton_job_option_dog_food_m")
        self.radioButton_job_option_dog_food_m.setGeometry(QRect(0, 0, 71, 21))
        self.radioButton_job_option_dog_food_m.setFont(font2)
        self.radioButton_job_option_dog_food_n = QRadioButton(self.groupBox_play_list_chapter)
        self.radioButton_job_option_dog_food_n.setObjectName(u"radioButton_job_option_dog_food_n")
        self.radioButton_job_option_dog_food_n.setGeometry(QRect(0, 30, 71, 21))
        self.radioButton_job_option_dog_food_n.setFont(font2)
        self.radioButton_job_option_dog_food_n.setChecked(True)
        self.checkBox_job_option_lock_cast = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_lock_cast.setObjectName(u"checkBox_job_option_lock_cast")
        self.checkBox_job_option_lock_cast.setGeometry(QRect(310, 20, 71, 21))
        self.checkBox_job_option_lock_cast.setFont(font2)
        self.checkBox_job_option_use_yingbing = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_use_yingbing.setObjectName(u"checkBox_job_option_use_yingbing")
        self.checkBox_job_option_use_yingbing.setGeometry(QRect(310, 50, 71, 21))
        self.checkBox_job_option_use_yingbing.setFont(font2)
        self.checkBox_job_option_gymnasium_mass = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_gymnasium_mass.setObjectName(u"checkBox_job_option_gymnasium_mass")
        self.checkBox_job_option_gymnasium_mass.setGeometry(QRect(490, 140, 51, 21))
        self.checkBox_job_option_gymnasium_mass.setFont(font2)
        self.checkBox_job_option_gymnasium_only_watch = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_gymnasium_only_watch.setObjectName(u"checkBox_job_option_gymnasium_only_watch")
        self.checkBox_job_option_gymnasium_only_watch.setGeometry(QRect(490, 170, 61, 21))
        self.checkBox_job_option_gymnasium_only_watch.setFont(font2)
        self.checkBox_job_option_encounter_boss = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_encounter_boss.setObjectName(u"checkBox_job_option_encounter_boss")
        self.checkBox_job_option_encounter_boss.setGeometry(QRect(150, 170, 81, 21))
        self.checkBox_job_option_encounter_boss.setFont(font2)
        self.groupBox_6 = QGroupBox(self.groupBox_play_list_setting)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(150, 20, 71, 141))
        self.radioButton_job_option_chapter_0v3 = QRadioButton(self.groupBox_6)
        self.radioButton_job_option_chapter_0v3.setObjectName(u"radioButton_job_option_chapter_0v3")
        self.radioButton_job_option_chapter_0v3.setGeometry(QRect(0, 60, 71, 21))
        self.radioButton_job_option_chapter_0v3.setFont(font2)
        self.radioButton_job_option_chapter_1v3 = QRadioButton(self.groupBox_6)
        self.radioButton_job_option_chapter_1v3.setObjectName(u"radioButton_job_option_chapter_1v3")
        self.radioButton_job_option_chapter_1v3.setGeometry(QRect(0, 30, 71, 21))
        self.radioButton_job_option_chapter_1v3.setFont(font2)
        self.radioButton_job_option_chapter_1v3.setChecked(False)
        self.radioButton_job_option_chapter_1v2 = QRadioButton(self.groupBox_6)
        self.radioButton_job_option_chapter_1v2.setObjectName(u"radioButton_job_option_chapter_1v2")
        self.radioButton_job_option_chapter_1v2.setGeometry(QRect(0, 90, 71, 21))
        self.radioButton_job_option_chapter_1v2.setFont(font2)
        self.radioButton_job_option_chapter_2v2 = QRadioButton(self.groupBox_6)
        self.radioButton_job_option_chapter_2v2.setObjectName(u"radioButton_job_option_chapter_2v2")
        self.radioButton_job_option_chapter_2v2.setGeometry(QRect(0, 0, 71, 21))
        self.radioButton_job_option_chapter_2v2.setFont(font2)
        self.radioButton_job_option_chapter_2v2.setChecked(True)
        self.radioButton_job_option_chapter_0v0 = QRadioButton(self.groupBox_6)
        self.radioButton_job_option_chapter_0v0.setObjectName(u"radioButton_job_option_chapter_0v0")
        self.radioButton_job_option_chapter_0v0.setGeometry(QRect(0, 120, 71, 21))
        self.radioButton_job_option_chapter_0v0.setFont(font2)
        self.groupBox_7 = QGroupBox(self.groupBox_play_list_setting)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(230, 80, 75, 81))
        self.radioButton_job_option_dog_food_star_4 = QRadioButton(self.groupBox_7)
        self.radioButton_job_option_dog_food_star_4.setObjectName(u"radioButton_job_option_dog_food_star_4")
        self.radioButton_job_option_dog_food_star_4.setGeometry(QRect(0, 60, 71, 21))
        self.radioButton_job_option_dog_food_star_4.setFont(font2)
        self.radioButton_job_option_dog_food_star_4.setChecked(False)
        self.radioButton_job_option_dog_food_star_2 = QRadioButton(self.groupBox_7)
        self.radioButton_job_option_dog_food_star_2.setObjectName(u"radioButton_job_option_dog_food_star_2")
        self.radioButton_job_option_dog_food_star_2.setGeometry(QRect(0, 0, 71, 21))
        self.radioButton_job_option_dog_food_star_2.setFont(font2)
        self.radioButton_job_option_dog_food_star_2.setChecked(True)
        self.radioButton_job_option_dog_food_star_3 = QRadioButton(self.groupBox_7)
        self.radioButton_job_option_dog_food_star_3.setObjectName(u"radioButton_job_option_dog_food_star_3")
        self.radioButton_job_option_dog_food_star_3.setGeometry(QRect(0, 30, 71, 21))
        self.radioButton_job_option_dog_food_star_3.setFont(font2)
        self.radioButton_job_option_dog_food_star_3.setChecked(False)
        self.checkBox_job_option_guild_mall_amulet = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_guild_mall_amulet.setObjectName(u"checkBox_job_option_guild_mall_amulet")
        self.checkBox_job_option_guild_mall_amulet.setGeometry(QRect(390, 80, 51, 21))
        self.checkBox_job_option_guild_mall_amulet.setFont(font2)
        self.checkBox_job_option_guild_mall_souls = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_guild_mall_souls.setObjectName(u"checkBox_job_option_guild_mall_souls")
        self.checkBox_job_option_guild_mall_souls.setGeometry(QRect(390, 50, 51, 21))
        self.checkBox_job_option_guild_mall_souls.setFont(font2)
        self.checkBox_job_option_guild_mall_skill_daruma = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_guild_mall_skill_daruma.setObjectName(u"checkBox_job_option_guild_mall_skill_daruma")
        self.checkBox_job_option_guild_mall_skill_daruma.setGeometry(QRect(390, 110, 51, 21))
        self.checkBox_job_option_guild_mall_skill_daruma.setFont(font2)
        self.checkBox_job_option_guild_mall_grade_daruma = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_guild_mall_grade_daruma.setObjectName(u"checkBox_job_option_guild_mall_grade_daruma")
        self.checkBox_job_option_guild_mall_grade_daruma.setGeometry(QRect(390, 20, 51, 21))
        self.checkBox_job_option_guild_mall_grade_daruma.setFont(font2)
        self.checkBox_job_option_guild_mall_skin_ticket = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_guild_mall_skin_ticket.setObjectName(u"checkBox_job_option_guild_mall_skin_ticket")
        self.checkBox_job_option_guild_mall_skin_ticket.setGeometry(QRect(390, 140, 51, 21))
        self.checkBox_job_option_guild_mall_skin_ticket.setFont(font2)
        self.checkBox_job_option_guild_mall_yingbing = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_guild_mall_yingbing.setObjectName(u"checkBox_job_option_guild_mall_yingbing")
        self.checkBox_job_option_guild_mall_yingbing.setGeometry(QRect(390, 170, 51, 21))
        self.checkBox_job_option_guild_mall_yingbing.setFont(font2)
        self.checkBox_job_option_story_buy_ap = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_story_buy_ap.setObjectName(u"checkBox_job_option_story_buy_ap")
        self.checkBox_job_option_story_buy_ap.setGeometry(QRect(310, 110, 71, 21))
        self.checkBox_job_option_story_buy_ap.setFont(font2)
        self.checkBox_job_option_story_realm_raid = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_story_realm_raid.setObjectName(u"checkBox_job_option_story_realm_raid")
        self.checkBox_job_option_story_realm_raid.setGeometry(QRect(230, 170, 71, 21))
        self.checkBox_job_option_story_realm_raid.setFont(font2)
        self.checkBox_job_option_failed_stop = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_failed_stop.setObjectName(u"checkBox_job_option_failed_stop")
        self.checkBox_job_option_failed_stop.setGeometry(QRect(310, 80, 71, 21))
        self.checkBox_job_option_failed_stop.setFont(font2)
        self.checkBox_job_option_ap_use_up_restart = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_ap_use_up_restart.setObjectName(u"checkBox_job_option_ap_use_up_restart")
        self.checkBox_job_option_ap_use_up_restart.setGeometry(QRect(310, 170, 71, 21))
        self.checkBox_job_option_ap_use_up_restart.setFont(font2)
        self.checkBox_job_option_ap_use_up_close_game = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_ap_use_up_close_game.setObjectName(u"checkBox_job_option_ap_use_up_close_game")
        self.checkBox_job_option_ap_use_up_close_game.setGeometry(QRect(310, 140, 71, 21))
        self.checkBox_job_option_ap_use_up_close_game.setFont(font2)
        self.checkBox_job_option_guild_coin = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_guild_coin.setObjectName(u"checkBox_job_option_guild_coin")
        self.checkBox_job_option_guild_coin.setGeometry(QRect(440, 20, 51, 21))
        self.checkBox_job_option_guild_coin.setFont(font2)
        self.checkBox_job_option_guild_contribute = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_guild_contribute.setObjectName(u"checkBox_job_option_guild_contribute")
        self.checkBox_job_option_guild_contribute.setGeometry(QRect(440, 50, 51, 21))
        self.checkBox_job_option_guild_contribute.setFont(font2)
        self.checkBox_job_option_guild_invocation = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_guild_invocation.setObjectName(u"checkBox_job_option_guild_invocation")
        self.checkBox_job_option_guild_invocation.setGeometry(QRect(440, 80, 51, 21))
        self.checkBox_job_option_guild_invocation.setFont(font2)
        self.checkBox_job_option_guild_task = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_guild_task.setObjectName(u"checkBox_job_option_guild_task")
        self.checkBox_job_option_guild_task.setGeometry(QRect(440, 140, 51, 21))
        self.checkBox_job_option_guild_task.setFont(font2)
        self.checkBox_job_option_guild_realm_ap = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_guild_realm_ap.setObjectName(u"checkBox_job_option_guild_realm_ap")
        self.checkBox_job_option_guild_realm_ap.setGeometry(QRect(440, 110, 51, 21))
        self.checkBox_job_option_guild_realm_ap.setFont(font2)
        self.checkBox_job_option_guild_foster_n = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_guild_foster_n.setObjectName(u"checkBox_job_option_guild_foster_n")
        self.checkBox_job_option_guild_foster_n.setGeometry(QRect(490, 50, 61, 21))
        self.checkBox_job_option_guild_foster_n.setFont(font2)
        self.checkBox_job_option_guild_foster_m = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_guild_foster_m.setObjectName(u"checkBox_job_option_guild_foster_m")
        self.checkBox_job_option_guild_foster_m.setGeometry(QRect(490, 20, 61, 21))
        self.checkBox_job_option_guild_foster_m.setFont(font2)
        self.checkBox_job_option_guild_cultivate_m = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_guild_cultivate_m.setObjectName(u"checkBox_job_option_guild_cultivate_m")
        self.checkBox_job_option_guild_cultivate_m.setGeometry(QRect(490, 80, 61, 21))
        self.checkBox_job_option_guild_cultivate_m.setFont(font2)
        self.checkBox_job_option_guild_cultivate_n = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_guild_cultivate_n.setObjectName(u"checkBox_job_option_guild_cultivate_n")
        self.checkBox_job_option_guild_cultivate_n.setGeometry(QRect(490, 110, 61, 21))
        self.checkBox_job_option_guild_cultivate_n.setFont(font2)
        self.checkBox_job_option_guild_task_contribute = QCheckBox(self.groupBox_play_list_setting)
        self.checkBox_job_option_guild_task_contribute.setObjectName(u"checkBox_job_option_guild_task_contribute")
        self.checkBox_job_option_guild_task_contribute.setGeometry(QRect(440, 170, 51, 21))
        self.checkBox_job_option_guild_task_contribute.setFont(font2)
        self.groupBox_32 = QGroupBox(self.tab_products)
        self.groupBox_32.setObjectName(u"groupBox_32")
        self.groupBox_32.setGeometry(QRect(790, 200, 71, 191))
        self.groupBox_32.setFont(font1)
        self.checkBox_play_list_option_accept_jade_cooperation = QCheckBox(self.groupBox_32)
        self.checkBox_play_list_option_accept_jade_cooperation.setObjectName(u"checkBox_play_list_option_accept_jade_cooperation")
        self.checkBox_play_list_option_accept_jade_cooperation.setGeometry(QRect(10, 20, 61, 21))
        self.checkBox_play_list_option_accept_jade_cooperation.setFont(font2)
        self.checkBox_play_list_option_accept_ap_cooperation = QCheckBox(self.groupBox_32)
        self.checkBox_play_list_option_accept_ap_cooperation.setObjectName(u"checkBox_play_list_option_accept_ap_cooperation")
        self.checkBox_play_list_option_accept_ap_cooperation.setGeometry(QRect(10, 50, 61, 21))
        self.checkBox_play_list_option_accept_ap_cooperation.setFont(font2)
        self.checkBox_play_list_option_accept_coin_cooperation = QCheckBox(self.groupBox_32)
        self.checkBox_play_list_option_accept_coin_cooperation.setObjectName(u"checkBox_play_list_option_accept_coin_cooperation")
        self.checkBox_play_list_option_accept_coin_cooperation.setGeometry(QRect(10, 140, 61, 21))
        self.checkBox_play_list_option_accept_coin_cooperation.setFont(font2)
        self.checkBox_play_list_option_accept_pet_cooperation = QCheckBox(self.groupBox_32)
        self.checkBox_play_list_option_accept_pet_cooperation.setObjectName(u"checkBox_play_list_option_accept_pet_cooperation")
        self.checkBox_play_list_option_accept_pet_cooperation.setGeometry(QRect(10, 110, 61, 21))
        self.checkBox_play_list_option_accept_pet_cooperation.setFont(font2)
        self.checkBox_play_list_option_accept_yingbing_cooperation_2 = QCheckBox(self.groupBox_32)
        self.checkBox_play_list_option_accept_yingbing_cooperation_2.setObjectName(u"checkBox_play_list_option_accept_yingbing_cooperation_2")
        self.checkBox_play_list_option_accept_yingbing_cooperation_2.setGeometry(QRect(10, 80, 61, 21))
        self.checkBox_play_list_option_accept_yingbing_cooperation_2.setFont(font2)
        self.checkBox_play_list_option_accept_yingbing_cooperation = QCheckBox(self.groupBox_32)
        self.checkBox_play_list_option_accept_yingbing_cooperation.setObjectName(u"checkBox_play_list_option_accept_yingbing_cooperation")
        self.checkBox_play_list_option_accept_yingbing_cooperation.setGeometry(QRect(10, 170, 61, 21))
        self.checkBox_play_list_option_accept_yingbing_cooperation.setFont(font2)
        self.tabWidget.addTab(self.tab_products, "")
        self.tab_plan_single = QWidget()
        self.tab_plan_single.setObjectName(u"tab_plan_single")
        self.groupBox_play_list_6 = QGroupBox(self.tab_plan_single)
        self.groupBox_play_list_6.setObjectName(u"groupBox_play_list_6")
        self.groupBox_play_list_6.setGeometry(QRect(10, 10, 421, 381))
        self.groupBox_play_list_6.setFont(font1)
        self.tableWidget_plan_single = QTableWidget(self.groupBox_play_list_6)
        self.tableWidget_plan_single.setObjectName(u"tableWidget_plan_single")
        self.tableWidget_plan_single.setGeometry(QRect(0, 20, 421, 361))
        self.tableWidget_plan_single.setFont(font1)
        self.tableWidget_plan_single.setContextMenuPolicy(Qt.CustomContextMenu)
        self.tableWidget_plan_single.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget_plan_single.setSelectionMode(QAbstractItemView.ExtendedSelection)
        self.tableWidget_plan_single.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableWidget_plan_single.setVerticalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_plan_single.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_plan_single.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_plan_single.horizontalHeader().setDefaultSectionSize(70)
        self.tableWidget_plan_single.horizontalHeader().setHighlightSections(False)
        self.tableWidget_plan_single.verticalHeader().setVisible(False)
        self.tableWidget_plan_single.verticalHeader().setMinimumSectionSize(18)
        self.tableWidget_plan_single.verticalHeader().setDefaultSectionSize(18)
        self.groupBox_sub_play_list_6 = QGroupBox(self.tab_plan_single)
        self.groupBox_sub_play_list_6.setObjectName(u"groupBox_sub_play_list_6")
        self.groupBox_sub_play_list_6.setGeometry(QRect(440, 10, 421, 381))
        self.groupBox_sub_play_list_6.setFont(font1)
        self.groupBox_sub_play_list_6.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.tableWidget_plan_single_sub = QTableWidget(self.groupBox_sub_play_list_6)
        self.tableWidget_plan_single_sub.setObjectName(u"tableWidget_plan_single_sub")
        self.tableWidget_plan_single_sub.setGeometry(QRect(0, 20, 421, 361))
        self.tableWidget_plan_single_sub.setFont(font1)
        self.tableWidget_plan_single_sub.setContextMenuPolicy(Qt.CustomContextMenu)
        self.tableWidget_plan_single_sub.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget_plan_single_sub.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableWidget_plan_single_sub.setVerticalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_plan_single_sub.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_plan_single_sub.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_plan_single_sub.horizontalHeader().setDefaultSectionSize(70)
        self.tableWidget_plan_single_sub.horizontalHeader().setHighlightSections(False)
        self.tableWidget_plan_single_sub.verticalHeader().setVisible(False)
        self.tableWidget_plan_single_sub.verticalHeader().setMinimumSectionSize(18)
        self.tableWidget_plan_single_sub.verticalHeader().setDefaultSectionSize(18)
        self.tabWidget.addTab(self.tab_plan_single, "")
        self.tab_plan_day = QWidget()
        self.tab_plan_day.setObjectName(u"tab_plan_day")
        self.groupBox_play_list_5 = QGroupBox(self.tab_plan_day)
        self.groupBox_play_list_5.setObjectName(u"groupBox_play_list_5")
        self.groupBox_play_list_5.setGeometry(QRect(10, 10, 421, 381))
        self.groupBox_play_list_5.setFont(font1)
        self.tableWidget_plan_day = QTableWidget(self.groupBox_play_list_5)
        self.tableWidget_plan_day.setObjectName(u"tableWidget_plan_day")
        self.tableWidget_plan_day.setGeometry(QRect(0, 20, 421, 361))
        self.tableWidget_plan_day.setFont(font1)
        self.tableWidget_plan_day.setContextMenuPolicy(Qt.CustomContextMenu)
        self.tableWidget_plan_day.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget_plan_day.setSelectionMode(QAbstractItemView.ExtendedSelection)
        self.tableWidget_plan_day.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableWidget_plan_day.setVerticalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_plan_day.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_plan_day.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_plan_day.horizontalHeader().setDefaultSectionSize(70)
        self.tableWidget_plan_day.horizontalHeader().setHighlightSections(False)
        self.tableWidget_plan_day.verticalHeader().setVisible(False)
        self.tableWidget_plan_day.verticalHeader().setMinimumSectionSize(18)
        self.tableWidget_plan_day.verticalHeader().setDefaultSectionSize(18)
        self.groupBox_sub_play_list_5 = QGroupBox(self.tab_plan_day)
        self.groupBox_sub_play_list_5.setObjectName(u"groupBox_sub_play_list_5")
        self.groupBox_sub_play_list_5.setGeometry(QRect(440, 10, 421, 381))
        self.groupBox_sub_play_list_5.setFont(font1)
        self.groupBox_sub_play_list_5.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.tableWidget_plan_day_sub = QTableWidget(self.groupBox_sub_play_list_5)
        self.tableWidget_plan_day_sub.setObjectName(u"tableWidget_plan_day_sub")
        self.tableWidget_plan_day_sub.setGeometry(QRect(0, 20, 421, 361))
        self.tableWidget_plan_day_sub.setFont(font1)
        self.tableWidget_plan_day_sub.setContextMenuPolicy(Qt.CustomContextMenu)
        self.tableWidget_plan_day_sub.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget_plan_day_sub.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableWidget_plan_day_sub.setVerticalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_plan_day_sub.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_plan_day_sub.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_plan_day_sub.horizontalHeader().setDefaultSectionSize(70)
        self.tableWidget_plan_day_sub.horizontalHeader().setHighlightSections(False)
        self.tableWidget_plan_day_sub.verticalHeader().setVisible(False)
        self.tableWidget_plan_day_sub.verticalHeader().setMinimumSectionSize(18)
        self.tableWidget_plan_day_sub.verticalHeader().setDefaultSectionSize(18)
        self.tabWidget.addTab(self.tab_plan_day, "")
        self.tab_plan_week = QWidget()
        self.tab_plan_week.setObjectName(u"tab_plan_week")
        self.groupBox_play_list_2 = QGroupBox(self.tab_plan_week)
        self.groupBox_play_list_2.setObjectName(u"groupBox_play_list_2")
        self.groupBox_play_list_2.setGeometry(QRect(10, 10, 421, 381))
        self.groupBox_play_list_2.setFont(font1)
        self.tableWidget_plan_week = QTableWidget(self.groupBox_play_list_2)
        self.tableWidget_plan_week.setObjectName(u"tableWidget_plan_week")
        self.tableWidget_plan_week.setGeometry(QRect(0, 20, 421, 361))
        self.tableWidget_plan_week.setFont(font1)
        self.tableWidget_plan_week.setContextMenuPolicy(Qt.CustomContextMenu)
        self.tableWidget_plan_week.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget_plan_week.setSelectionMode(QAbstractItemView.ExtendedSelection)
        self.tableWidget_plan_week.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableWidget_plan_week.setVerticalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_plan_week.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_plan_week.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_plan_week.horizontalHeader().setDefaultSectionSize(70)
        self.tableWidget_plan_week.horizontalHeader().setHighlightSections(False)
        self.tableWidget_plan_week.verticalHeader().setVisible(False)
        self.tableWidget_plan_week.verticalHeader().setMinimumSectionSize(18)
        self.tableWidget_plan_week.verticalHeader().setDefaultSectionSize(18)
        self.groupBox_sub_play_list_2 = QGroupBox(self.tab_plan_week)
        self.groupBox_sub_play_list_2.setObjectName(u"groupBox_sub_play_list_2")
        self.groupBox_sub_play_list_2.setGeometry(QRect(440, 10, 421, 381))
        self.groupBox_sub_play_list_2.setFont(font1)
        self.groupBox_sub_play_list_2.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.tableWidget_plan_week_sub = QTableWidget(self.groupBox_sub_play_list_2)
        self.tableWidget_plan_week_sub.setObjectName(u"tableWidget_plan_week_sub")
        self.tableWidget_plan_week_sub.setGeometry(QRect(0, 20, 421, 361))
        self.tableWidget_plan_week_sub.setFont(font1)
        self.tableWidget_plan_week_sub.setContextMenuPolicy(Qt.CustomContextMenu)
        self.tableWidget_plan_week_sub.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget_plan_week_sub.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableWidget_plan_week_sub.setVerticalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_plan_week_sub.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_plan_week_sub.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_plan_week_sub.horizontalHeader().setDefaultSectionSize(70)
        self.tableWidget_plan_week_sub.horizontalHeader().setHighlightSections(False)
        self.tableWidget_plan_week_sub.verticalHeader().setVisible(False)
        self.tableWidget_plan_week_sub.verticalHeader().setMinimumSectionSize(18)
        self.tableWidget_plan_week_sub.verticalHeader().setDefaultSectionSize(18)
        self.tabWidget.addTab(self.tab_plan_week, "")
        self.tab_plan_month = QWidget()
        self.tab_plan_month.setObjectName(u"tab_plan_month")
        self.groupBox_play_list_7 = QGroupBox(self.tab_plan_month)
        self.groupBox_play_list_7.setObjectName(u"groupBox_play_list_7")
        self.groupBox_play_list_7.setGeometry(QRect(10, 10, 421, 381))
        self.groupBox_play_list_7.setFont(font1)
        self.tableWidget_plan_month = QTableWidget(self.groupBox_play_list_7)
        self.tableWidget_plan_month.setObjectName(u"tableWidget_plan_month")
        self.tableWidget_plan_month.setGeometry(QRect(0, 20, 421, 361))
        self.tableWidget_plan_month.setFont(font1)
        self.tableWidget_plan_month.setContextMenuPolicy(Qt.CustomContextMenu)
        self.tableWidget_plan_month.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget_plan_month.setSelectionMode(QAbstractItemView.ExtendedSelection)
        self.tableWidget_plan_month.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableWidget_plan_month.setVerticalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_plan_month.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_plan_month.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_plan_month.horizontalHeader().setDefaultSectionSize(70)
        self.tableWidget_plan_month.horizontalHeader().setHighlightSections(False)
        self.tableWidget_plan_month.verticalHeader().setVisible(False)
        self.tableWidget_plan_month.verticalHeader().setMinimumSectionSize(18)
        self.tableWidget_plan_month.verticalHeader().setDefaultSectionSize(18)
        self.groupBox_sub_play_list_7 = QGroupBox(self.tab_plan_month)
        self.groupBox_sub_play_list_7.setObjectName(u"groupBox_sub_play_list_7")
        self.groupBox_sub_play_list_7.setGeometry(QRect(440, 10, 421, 381))
        self.groupBox_sub_play_list_7.setFont(font1)
        self.groupBox_sub_play_list_7.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.tableWidget_plan_month_sub = QTableWidget(self.groupBox_sub_play_list_7)
        self.tableWidget_plan_month_sub.setObjectName(u"tableWidget_plan_month_sub")
        self.tableWidget_plan_month_sub.setGeometry(QRect(0, 20, 421, 361))
        self.tableWidget_plan_month_sub.setFont(font1)
        self.tableWidget_plan_month_sub.setContextMenuPolicy(Qt.CustomContextMenu)
        self.tableWidget_plan_month_sub.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget_plan_month_sub.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableWidget_plan_month_sub.setVerticalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_plan_month_sub.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_plan_month_sub.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_plan_month_sub.horizontalHeader().setDefaultSectionSize(70)
        self.tableWidget_plan_month_sub.horizontalHeader().setHighlightSections(False)
        self.tableWidget_plan_month_sub.verticalHeader().setVisible(False)
        self.tableWidget_plan_month_sub.verticalHeader().setMinimumSectionSize(18)
        self.tableWidget_plan_month_sub.verticalHeader().setDefaultSectionSize(18)
        self.tabWidget.addTab(self.tab_plan_month, "")
        self.tab_account = QWidget()
        self.tab_account.setObjectName(u"tab_account")
        self.groupBox_play_list_8 = QGroupBox(self.tab_account)
        self.groupBox_play_list_8.setObjectName(u"groupBox_play_list_8")
        self.groupBox_play_list_8.setGeometry(QRect(10, 10, 851, 401))
        self.groupBox_play_list_8.setFont(font1)
        self.tableWidget_account = QTableWidget(self.groupBox_play_list_8)
        self.tableWidget_account.setObjectName(u"tableWidget_account")
        self.tableWidget_account.setGeometry(QRect(0, 20, 841, 381))
        self.tableWidget_account.setFont(font1)
        self.tableWidget_account.setContextMenuPolicy(Qt.CustomContextMenu)
        self.tableWidget_account.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget_account.setSelectionMode(QAbstractItemView.ExtendedSelection)
        self.tableWidget_account.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableWidget_account.setVerticalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_account.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_account.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_account.horizontalHeader().setDefaultSectionSize(70)
        self.tableWidget_account.horizontalHeader().setHighlightSections(False)
        self.tableWidget_account.verticalHeader().setVisible(False)
        self.tableWidget_account.verticalHeader().setMinimumSectionSize(18)
        self.tableWidget_account.verticalHeader().setDefaultSectionSize(18)
        self.tabWidget.addTab(self.tab_account, "")
        self.tab_emulator_sandbox = QWidget()
        self.tab_emulator_sandbox.setObjectName(u"tab_emulator_sandbox")
        self.groupBox_play_list_9 = QGroupBox(self.tab_emulator_sandbox)
        self.groupBox_play_list_9.setObjectName(u"groupBox_play_list_9")
        self.groupBox_play_list_9.setGeometry(QRect(10, 10, 251, 381))
        self.groupBox_play_list_9.setFont(font1)
        self.tableWidget_emulator = QTableWidget(self.groupBox_play_list_9)
        self.tableWidget_emulator.setObjectName(u"tableWidget_emulator")
        self.tableWidget_emulator.setGeometry(QRect(0, 20, 251, 361))
        self.tableWidget_emulator.setFont(font1)
        self.tableWidget_emulator.setContextMenuPolicy(Qt.CustomContextMenu)
        self.tableWidget_emulator.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget_emulator.setSelectionMode(QAbstractItemView.ExtendedSelection)
        self.tableWidget_emulator.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableWidget_emulator.setVerticalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_emulator.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_emulator.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_emulator.horizontalHeader().setDefaultSectionSize(70)
        self.tableWidget_emulator.horizontalHeader().setHighlightSections(False)
        self.tableWidget_emulator.verticalHeader().setVisible(False)
        self.tableWidget_emulator.verticalHeader().setMinimumSectionSize(18)
        self.tableWidget_emulator.verticalHeader().setDefaultSectionSize(18)
        self.groupBox_play_list_11 = QGroupBox(self.tab_emulator_sandbox)
        self.groupBox_play_list_11.setObjectName(u"groupBox_play_list_11")
        self.groupBox_play_list_11.setGeometry(QRect(280, 10, 251, 381))
        self.groupBox_play_list_11.setFont(font1)
        self.tableWidget_sandbox = QTableWidget(self.groupBox_play_list_11)
        self.tableWidget_sandbox.setObjectName(u"tableWidget_sandbox")
        self.tableWidget_sandbox.setGeometry(QRect(0, 20, 251, 361))
        self.tableWidget_sandbox.setFont(font1)
        self.tableWidget_sandbox.setContextMenuPolicy(Qt.CustomContextMenu)
        self.tableWidget_sandbox.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget_sandbox.setSelectionMode(QAbstractItemView.ExtendedSelection)
        self.tableWidget_sandbox.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableWidget_sandbox.setVerticalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_sandbox.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget_sandbox.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_sandbox.horizontalHeader().setDefaultSectionSize(70)
        self.tableWidget_sandbox.horizontalHeader().setHighlightSections(False)
        self.tableWidget_sandbox.verticalHeader().setVisible(False)
        self.tableWidget_sandbox.verticalHeader().setMinimumSectionSize(18)
        self.tableWidget_sandbox.verticalHeader().setDefaultSectionSize(18)
        self.groupBox_dnplayer_path = QGroupBox(self.tab_emulator_sandbox)
        self.groupBox_dnplayer_path.setObjectName(u"groupBox_dnplayer_path")
        self.groupBox_dnplayer_path.setGeometry(QRect(550, 130, 301, 51))
        self.groupBox_dnplayer_path.setFont(font1)
        self.pushButton_browse_dnplayer_path = QPushButton(self.groupBox_dnplayer_path)
        self.pushButton_browse_dnplayer_path.setObjectName(u"pushButton_browse_dnplayer_path")
        self.pushButton_browse_dnplayer_path.setGeometry(QRect(240, 19, 51, 23))
        self.pushButton_browse_dnplayer_path.setFont(font1)
        self.lineEdit_dnplayer_path = QLineEdit(self.groupBox_dnplayer_path)
        self.lineEdit_dnplayer_path.setObjectName(u"lineEdit_dnplayer_path")
        self.lineEdit_dnplayer_path.setGeometry(QRect(10, 20, 231, 21))
        font3 = QFont()
        font3.setFamilies([u"\u5b8b\u4f53"])
        font3.setPointSize(9)
        self.lineEdit_dnplayer_path.setFont(font3)
        self.lineEdit_dnplayer_path.setReadOnly(True)
        self.groupBox_dnplayer_path_3 = QGroupBox(self.tab_emulator_sandbox)
        self.groupBox_dnplayer_path_3.setObjectName(u"groupBox_dnplayer_path_3")
        self.groupBox_dnplayer_path_3.setGeometry(QRect(550, 70, 301, 51))
        self.groupBox_dnplayer_path_3.setFont(font1)
        self.pushButton_browse_sandbox_path = QPushButton(self.groupBox_dnplayer_path_3)
        self.pushButton_browse_sandbox_path.setObjectName(u"pushButton_browse_sandbox_path")
        self.pushButton_browse_sandbox_path.setGeometry(QRect(240, 19, 51, 23))
        self.pushButton_browse_sandbox_path.setFont(font1)
        self.lineEdit_sandbox_path = QLineEdit(self.groupBox_dnplayer_path_3)
        self.lineEdit_sandbox_path.setObjectName(u"lineEdit_sandbox_path")
        self.lineEdit_sandbox_path.setGeometry(QRect(10, 20, 231, 21))
        self.lineEdit_sandbox_path.setFont(font3)
        self.lineEdit_sandbox_path.setReadOnly(True)
        self.groupBox_dnplayer_path_4 = QGroupBox(self.tab_emulator_sandbox)
        self.groupBox_dnplayer_path_4.setObjectName(u"groupBox_dnplayer_path_4")
        self.groupBox_dnplayer_path_4.setGeometry(QRect(550, 10, 301, 51))
        self.groupBox_dnplayer_path_4.setFont(font1)
        self.pushButton_browse_onmyoji_pc_path = QPushButton(self.groupBox_dnplayer_path_4)
        self.pushButton_browse_onmyoji_pc_path.setObjectName(u"pushButton_browse_onmyoji_pc_path")
        self.pushButton_browse_onmyoji_pc_path.setGeometry(QRect(240, 19, 51, 23))
        self.pushButton_browse_onmyoji_pc_path.setFont(font1)
        self.lineEdit_onmyoji_pc_path = QLineEdit(self.groupBox_dnplayer_path_4)
        self.lineEdit_onmyoji_pc_path.setObjectName(u"lineEdit_onmyoji_pc_path")
        self.lineEdit_onmyoji_pc_path.setGeometry(QRect(10, 20, 231, 21))
        self.lineEdit_onmyoji_pc_path.setFont(font3)
        self.lineEdit_onmyoji_pc_path.setReadOnly(True)
        self.groupBox_31 = QGroupBox(self.tab_emulator_sandbox)
        self.groupBox_31.setObjectName(u"groupBox_31")
        self.groupBox_31.setGeometry(QRect(550, 190, 301, 51))
        self.groupBox_31.setFont(font1)
        self.groupBox__run_count_2 = QGroupBox(self.groupBox_31)
        self.groupBox__run_count_2.setObjectName(u"groupBox__run_count_2")
        self.groupBox__run_count_2.setEnabled(True)
        self.groupBox__run_count_2.setGeometry(QRect(140, 20, 151, 23))
        self.groupBox__run_count_2.setFont(font)
        self.spinBox_scroll_time = QSpinBox(self.groupBox__run_count_2)
        self.spinBox_scroll_time.setObjectName(u"spinBox_scroll_time")
        self.spinBox_scroll_time.setGeometry(QRect(60, 1, 51, 20))
        self.spinBox_scroll_time.setFont(font1)
        self.spinBox_scroll_time.setMinimum(1)
        self.spinBox_scroll_time.setMaximum(1440)
        self.spinBox_scroll_time.setValue(60)
        self.label_scroll_time = QLabel(self.groupBox__run_count_2)
        self.label_scroll_time.setObjectName(u"label_scroll_time")
        self.label_scroll_time.setGeometry(QRect(10, 0, 61, 21))
        self.label_scroll_time.setFont(font1)
        self.label_run_count_3 = QLabel(self.groupBox__run_count_2)
        self.label_run_count_3.setObjectName(u"label_run_count_3")
        self.label_run_count_3.setGeometry(QRect(120, 0, 31, 21))
        self.label_run_count_3.setFont(font1)
        self.groupBox__run_count = QGroupBox(self.groupBox_31)
        self.groupBox__run_count.setObjectName(u"groupBox__run_count")
        self.groupBox__run_count.setEnabled(True)
        self.groupBox__run_count.setGeometry(QRect(10, 20, 121, 23))
        self.groupBox__run_count.setFont(font)
        self.spinBox_scroll_count = QSpinBox(self.groupBox__run_count)
        self.spinBox_scroll_count.setObjectName(u"spinBox_scroll_count")
        self.spinBox_scroll_count.setGeometry(QRect(80, 1, 41, 20))
        self.spinBox_scroll_count.setFont(font1)
        self.spinBox_scroll_count.setMaximum(99)
        self.spinBox_scroll_count.setValue(10)
        self.label_scroll_count = QLabel(self.groupBox__run_count)
        self.label_scroll_count.setObjectName(u"label_scroll_count")
        self.label_scroll_count.setGeometry(QRect(10, 0, 61, 21))
        self.label_scroll_count.setFont(font1)
        self.groupBox_dnplayer_path_2 = QGroupBox(self.tab_emulator_sandbox)
        self.groupBox_dnplayer_path_2.setObjectName(u"groupBox_dnplayer_path_2")
        self.groupBox_dnplayer_path_2.setGeometry(QRect(550, 250, 301, 51))
        self.groupBox_dnplayer_path_2.setFont(font1)
        self.groupBox__run_count_3 = QGroupBox(self.groupBox_dnplayer_path_2)
        self.groupBox__run_count_3.setObjectName(u"groupBox__run_count_3")
        self.groupBox__run_count_3.setEnabled(True)
        self.groupBox__run_count_3.setGeometry(QRect(10, 20, 281, 23))
        self.groupBox__run_count_3.setFont(font)
        self.spinBox_cpu_sleep_time = QSpinBox(self.groupBox__run_count_3)
        self.spinBox_cpu_sleep_time.setObjectName(u"spinBox_cpu_sleep_time")
        self.spinBox_cpu_sleep_time.setGeometry(QRect(190, 1, 51, 20))
        self.spinBox_cpu_sleep_time.setFont(font1)
        self.spinBox_cpu_sleep_time.setMaximum(24)
        self.spinBox_cpu_sleep_time.setValue(7)
        self.label_scroll_count_2 = QLabel(self.groupBox__run_count_3)
        self.label_scroll_count_2.setObjectName(u"label_scroll_count_2")
        self.label_scroll_count_2.setGeometry(QRect(10, 0, 161, 21))
        self.label_scroll_count_2.setFont(font1)
        self.groupBox = QGroupBox(self.tab_emulator_sandbox)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(550, 320, 301, 61))
        self.checkBox = QCheckBox(self.groupBox)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(20, 30, 121, 16))
        self.tabWidget.addTab(self.tab_emulator_sandbox, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"HiWorker", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_run_list), QCoreApplication.translate("MainWindow", u"\u5de5\u5382", None))
        self.groupBox_play_list.setTitle(QCoreApplication.translate("MainWindow", u"\u4ea7\u54c1\u5217\u8868", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"\u73a9\u6cd5", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u5185\u5bb9", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u6b21\u6570", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u96be\u5ea6", None))
        self.pushButton_save_job.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58", None))
        self.pushButton_reset_job_option.setText(QCoreApplication.translate("MainWindow", u"\u91cd\u7f6e", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u5b50\u9879", None))
        self.checkBox_job_option_approximate_count.setText(QCoreApplication.translate("MainWindow", u"\u6b21\u6570\u8fd1\u4f3c\u6a21\u5f0f", None))
        self.groupBox_play_list_setting.setTitle(QCoreApplication.translate("MainWindow", u"\u53c2\u6570", None))
        self.checkBox_job_option_bonus_exp_100.setText(QCoreApplication.translate("MainWindow", u"\u4e00\u767e\u7ecf\u9a8c", None))
        self.checkBox_job_option_bonus_exp_50.setText(QCoreApplication.translate("MainWindow", u"\u4e94\u5341\u7ecf\u9a8c", None))
        self.checkBox_job_option_bonus_coin_100.setText(QCoreApplication.translate("MainWindow", u"\u4e00\u767e\u91d1\u5e01", None))
        self.checkBox_job_option_bonus_evolution.setText(QCoreApplication.translate("MainWindow", u"\u89c9\u9192\u52a0\u6210", None))
        self.checkBox_job_option_bonus_coin_50.setText(QCoreApplication.translate("MainWindow", u"\u4e94\u5341\u91d1\u5e01", None))
        self.checkBox_job_option_bonus_soul.setText(QCoreApplication.translate("MainWindow", u"\u5fa1\u9b42\u52a0\u6210", None))
        self.checkBox_job_option_chapter_gift_spirit.setText(QCoreApplication.translate("MainWindow", u"\u7269\u54c1\u602a", None))
        self.checkBox_job_option_chapter_exp_spirit.setText(QCoreApplication.translate("MainWindow", u"\u7ecf\u9a8c\u602a", None))
        self.checkBox_job_option_chapter_all_spirit.setText(QCoreApplication.translate("MainWindow", u"\u6240\u6709\u602a", None))
        self.checkBox_job_option_chapter_coin_spirit.setText(QCoreApplication.translate("MainWindow", u"\u91d1\u5e01\u602a", None))
        self.checkBox_job_option_chapter_map_gift.setText(QCoreApplication.translate("MainWindow", u"\u5730\u56fe\u5956", None))
        self.checkBox_job_option_chapter_map_seal.setText(QCoreApplication.translate("MainWindow", u"\u5996\u6c14\u5c01", None))
        self.groupBox_play_list_chapter.setTitle("")
        self.radioButton_job_option_dog_food_m.setText(QCoreApplication.translate("MainWindow", u"\u72d7\u7cae\u00b7\u767d\u86cb", None))
        self.radioButton_job_option_dog_food_n.setText(QCoreApplication.translate("MainWindow", u"\u72d7\u7cae\u00b7N\u5361", None))
        self.checkBox_job_option_lock_cast.setText(QCoreApplication.translate("MainWindow", u"\u9501\u5b9a\u9635\u5bb9", None))
        self.checkBox_job_option_use_yingbing.setText(QCoreApplication.translate("MainWindow", u"\u4f7f\u7528\u6a31\u997c", None))
        self.checkBox_job_option_gymnasium_mass.setText(QCoreApplication.translate("MainWindow", u"\u96c6\u7ed3", None))
        self.checkBox_job_option_gymnasium_only_watch.setText(QCoreApplication.translate("MainWindow", u"\u4ec5\u89c2\u6218", None))
        self.checkBox_job_option_encounter_boss.setText(QCoreApplication.translate("MainWindow", u"\u9022\u9b54\u00b7Boss", None))
        self.groupBox_6.setTitle("")
        self.radioButton_job_option_chapter_0v3.setText(QCoreApplication.translate("MainWindow", u"\u72d7\u7cae\u00b70v3", None))
        self.radioButton_job_option_chapter_1v3.setText(QCoreApplication.translate("MainWindow", u"\u72d7\u7cae\u00b71v3", None))
        self.radioButton_job_option_chapter_1v2.setText(QCoreApplication.translate("MainWindow", u"\u72d7\u7cae\u00b71v2", None))
        self.radioButton_job_option_chapter_2v2.setText(QCoreApplication.translate("MainWindow", u"\u72d7\u7cae\u00b72v2", None))
        self.radioButton_job_option_chapter_0v0.setText(QCoreApplication.translate("MainWindow", u"\u72d7\u7cae\u00b70v0", None))
        self.groupBox_7.setTitle("")
        self.radioButton_job_option_dog_food_star_4.setText(QCoreApplication.translate("MainWindow", u"\u72d7\u7cae\u00b7\u56db\u661f", None))
        self.radioButton_job_option_dog_food_star_2.setText(QCoreApplication.translate("MainWindow", u"\u72d7\u7cae\u00b7\u4e8c\u661f", None))
        self.radioButton_job_option_dog_food_star_3.setText(QCoreApplication.translate("MainWindow", u"\u72d7\u7cae\u00b7\u4e09\u661f", None))
        self.checkBox_job_option_guild_mall_amulet.setText(QCoreApplication.translate("MainWindow", u"\u84dd\u7968", None))
        self.checkBox_job_option_guild_mall_souls.setText(QCoreApplication.translate("MainWindow", u"\u5fa1\u9b42", None))
        self.checkBox_job_option_guild_mall_skill_daruma.setText(QCoreApplication.translate("MainWindow", u"\u9ed1\u76ae", None))
        self.checkBox_job_option_guild_mall_grade_daruma.setText(QCoreApplication.translate("MainWindow", u"\u767d\u86cb", None))
        self.checkBox_job_option_guild_mall_skin_ticket.setText(QCoreApplication.translate("MainWindow", u"\u76ae\u5238", None))
        self.checkBox_job_option_guild_mall_yingbing.setText(QCoreApplication.translate("MainWindow", u"\u6a31\u997c", None))
        self.checkBox_job_option_story_buy_ap.setText(QCoreApplication.translate("MainWindow", u"\u5267\u60c5\u00b7\u4e70\u4f53", None))
        self.checkBox_job_option_story_realm_raid.setText(QCoreApplication.translate("MainWindow", u"\u5267\u60c5\u00b7\u7a81\u7834", None))
        self.checkBox_job_option_failed_stop.setText(QCoreApplication.translate("MainWindow", u"\u5931\u8d25\u00b7\u505c\u6b62", None))
        self.checkBox_job_option_ap_use_up_restart.setText(QCoreApplication.translate("MainWindow", u"\u65e0\u4f53\u00b7\u91cd\u5f00", None))
        self.checkBox_job_option_ap_use_up_close_game.setText(QCoreApplication.translate("MainWindow", u"\u65e0\u4f53\u00b7\u5173\u6e38", None))
        self.checkBox_job_option_guild_coin.setText(QCoreApplication.translate("MainWindow", u"\u91d1\u5e01", None))
        self.checkBox_job_option_guild_contribute.setText(QCoreApplication.translate("MainWindow", u"\u6350\u52fe", None))
        self.checkBox_job_option_guild_invocation.setText(QCoreApplication.translate("MainWindow", u"\u7948\u613f", None))
        self.checkBox_job_option_guild_task.setText(QCoreApplication.translate("MainWindow", u"\u7ed3\u4f34", None))
        self.checkBox_job_option_guild_realm_ap.setText(QCoreApplication.translate("MainWindow", u"\u4f53\u529b", None))
        self.checkBox_job_option_guild_foster_n.setText(QCoreApplication.translate("MainWindow", u"\u5bc4\u517b\u00b7N", None))
        self.checkBox_job_option_guild_foster_m.setText(QCoreApplication.translate("MainWindow", u"\u5bc4\u517b\u00b7M", None))
        self.checkBox_job_option_guild_cultivate_m.setText(QCoreApplication.translate("MainWindow", u"\u80b2\u6210\u00b7M", None))
        self.checkBox_job_option_guild_cultivate_n.setText(QCoreApplication.translate("MainWindow", u"\u80b2\u6210\u00b7N", None))
        self.checkBox_job_option_guild_task_contribute.setText(QCoreApplication.translate("MainWindow", u"\u6350\u6750", None))
        self.groupBox_32.setTitle(QCoreApplication.translate("MainWindow", u"\u60ac\u8d4f\u5c01\u5370", None))
        self.checkBox_play_list_option_accept_jade_cooperation.setText(QCoreApplication.translate("MainWindow", u"\u63a5\u52fe\u7389", None))
        self.checkBox_play_list_option_accept_ap_cooperation.setText(QCoreApplication.translate("MainWindow", u"\u63a5\u4f53\u529b", None))
        self.checkBox_play_list_option_accept_coin_cooperation.setText(QCoreApplication.translate("MainWindow", u"\u63a5\u91d1\u5e01", None))
        self.checkBox_play_list_option_accept_pet_cooperation.setText(QCoreApplication.translate("MainWindow", u"\u63a5\u72d7\u7cae", None))
        self.checkBox_play_list_option_accept_yingbing_cooperation_2.setText(QCoreApplication.translate("MainWindow", u"\u63a5\u73b0\u4e16", None))
        self.checkBox_play_list_option_accept_yingbing_cooperation.setText(QCoreApplication.translate("MainWindow", u"\u63a5\u6a31\u997c", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_products), QCoreApplication.translate("MainWindow", u"\u4ea7\u54c1", None))
        self.groupBox_play_list_6.setTitle(QCoreApplication.translate("MainWindow", u"\u5355\u6b21\u8ba1\u5212\u5217\u8868", None))
        self.groupBox_sub_play_list_6.setTitle(QCoreApplication.translate("MainWindow", u"\u5355\u6b21\u8ba1\u5212\u5b50\u9879", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_plan_single), QCoreApplication.translate("MainWindow", u"\u5355\u6b21\u8ba1\u5212", None))
        self.groupBox_play_list_5.setTitle(QCoreApplication.translate("MainWindow", u"\u65e5\u8ba1\u5212\u5217\u8868", None))
        self.groupBox_sub_play_list_5.setTitle(QCoreApplication.translate("MainWindow", u"\u65e5\u8ba1\u5212\u5b50\u9879", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_plan_day), QCoreApplication.translate("MainWindow", u"\u65e5\u8ba1\u5212", None))
        self.groupBox_play_list_2.setTitle(QCoreApplication.translate("MainWindow", u"\u5468\u8ba1\u5212\u5217\u8868", None))
        self.groupBox_sub_play_list_2.setTitle(QCoreApplication.translate("MainWindow", u"\u5468\u8ba1\u5212\u5b50\u9879", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_plan_week), QCoreApplication.translate("MainWindow", u"\u5468\u8ba1\u5212", None))
        self.groupBox_play_list_7.setTitle(QCoreApplication.translate("MainWindow", u"\u6708\u8ba1\u5212\u5217\u8868", None))
        self.groupBox_sub_play_list_7.setTitle(QCoreApplication.translate("MainWindow", u"\u6708\u8ba1\u5212\u5b50\u9879", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_plan_month), QCoreApplication.translate("MainWindow", u"\u6708\u8ba1\u5212", None))
        self.groupBox_play_list_8.setTitle(QCoreApplication.translate("MainWindow", u"\u8d26\u53f7\u5217\u8868", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_account), QCoreApplication.translate("MainWindow", u"\u8d26\u6237", None))
        self.groupBox_play_list_9.setTitle(QCoreApplication.translate("MainWindow", u"\u6a21\u62df\u5668\u5217\u8868", None))
        self.groupBox_play_list_11.setTitle(QCoreApplication.translate("MainWindow", u"sandbox\u5217\u8868", None))
        self.groupBox_dnplayer_path.setTitle(QCoreApplication.translate("MainWindow", u"\u96f7\u7535\u6a21\u62df\u5668\u8def\u5f84", None))
        self.pushButton_browse_dnplayer_path.setText(QCoreApplication.translate("MainWindow", u"\u6d4f\u89c8", None))
        self.lineEdit_dnplayer_path.setText("")
        self.groupBox_dnplayer_path_3.setTitle(QCoreApplication.translate("MainWindow", u"sandbox\u8def\u5f84", None))
        self.pushButton_browse_sandbox_path.setText(QCoreApplication.translate("MainWindow", u"\u6d4f\u89c8", None))
        self.lineEdit_sandbox_path.setText("")
        self.groupBox_dnplayer_path_4.setTitle(QCoreApplication.translate("MainWindow", u"\u6e38\u620fPC\u7aef\u8def\u5f84", None))
        self.pushButton_browse_onmyoji_pc_path.setText(QCoreApplication.translate("MainWindow", u"\u6d4f\u89c8", None))
        self.lineEdit_onmyoji_pc_path.setText("")
        self.groupBox_31.setTitle(QCoreApplication.translate("MainWindow", u"\u8f6e\u6362\u8bbe\u7f6e", None))
        self.groupBox__run_count_2.setTitle("")
        self.label_scroll_time.setText(QCoreApplication.translate("MainWindow", u"\u6267\u884c\u65f6\u957f", None))
        self.label_run_count_3.setText(QCoreApplication.translate("MainWindow", u"\u5206\u949f", None))
        self.groupBox__run_count.setTitle("")
        self.label_scroll_count.setText(QCoreApplication.translate("MainWindow", u"\u540c\u65f6\u6267\u884c\u6570", None))
        self.groupBox_dnplayer_path_2.setTitle(QCoreApplication.translate("MainWindow", u"CPU\u8c03\u8282", None))
        self.groupBox__run_count_3.setTitle("")
        self.label_scroll_count_2.setText(QCoreApplication.translate("MainWindow", u"\u6570\u503c\u8d8a\u5927\u5360\u7528\u8d8a\u5c0f\uff0c\u6267\u884c\u8d8a\u6162", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"\u65e5\u8ba1\u5212\u5faa\u73af", None))
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"\u65e5\u8ba1\u5212\u5faa\u73af\u5f00\u542f", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_emulator_sandbox), QCoreApplication.translate("MainWindow", u"\u673a\u5668", None))
    # retranslateUi

