from .BossAttack import DetectBossAttack
from .BossDefense import DetectBossDefense
from .Daily import DetectDaily
from .DraftDuel import DetectDraftDuel
from .Duel import DetectDuel
from .Encounter import DetectEncounter
from .GuildFeast import DetectGuildFeast
from .Gymnasium import DetectGymnasium
from .NetherworldGate import DetectNetherworldGate
from .RoyalBattle import DetectRoyalBattle
